runtime: python
env: flex
entrypoint: streamlit run main.py --server.port $PORT --server.address 0.0.0.0

runtime_config:
  python_version: 3.11.0 # Match your Python version

resources:
  cpu: 1 # Adjust as needed (e.g., 2, 4)
  memory_gb: 2 # Adjust as needed (e.g., 4, 8)

